In [2]:
import pandas as pd
import numpy as np
import pickle
import warnings
warnings.filterwarnings('ignore')

In [25]:
df = pd.read_csv("data.csv")

df.drop(df.columns[[0, 1, 2,3]], axis=1, inplace=True)

In [26]:
df

,s_2,s_3,s_4,s_6,s_7,s_8,s_9,s_11,s_12,s_13,s_14,s_15,s_17,s_20,s_21
0,643.86,1612.86,1393.95,21.60,554.62,2388.08,9145.19,47.65,521.64,2388.13,8199.43,8.57,398.99,38.96,23.41
1,643.23,1571.79,1396.64,21.60,554.84,2388.00,9111.08,47.07,519.20,2388.56,8142.23,8.46,398.07,38.93,23.11
2,643.33,1595.09,1411.49,21.61,551.67,2388.41,9139.12,48.14,520.57,2388.49,8154.84,8.42,397.69,39.33,22.94
3,644.36,1595.17,1387.35,21.60,553.97,2388.49,9099.48,46.96,518.78,2388.19,8112.17,8.39,399.65,39.30,23.51
4,642.10,1595.80,1404.48,21.61,553.03,2388.34,9140.20,46.92,520.74,2388.51,8280.31,8.51,391.41,39.09,23.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,642.85,1612.90,1389.54,21.60,555.41,2387.93,9070.16,47.49,522.33,2388.23,8284.55,8.43,397.41,38.59,23.57
317,644.23,1574.47,1424.53,21.61,553.58,2387.99,9139.75,47.11,518.79,2388.13,8166.26,8.58,395.30,38.86,22.92
318,641.73,1573.36,1438.41,21.60,551.46,2388.46,9095.43,47.65,519.73,2387.95,8291.51,8.37,394.00,39.14,23.27
319,642.63,1602.41,1417.46,21.60,553.37,2388.03,9081.83,47.01,520.32,2388.08,8188.83,8.50,391.23,38.23,23.07
320,642.22,1581.31,1399.92,21.60,552.98,2388.27,9043.06,48.25,518.86,2388.10,8282.39,8.33,393.90,38.71,23.47

In [55]:
with open('finalized_model.sav', 'rb') as f:

        model = pickle.load(f)

d=df.copy()
ls=[]
for i in range(0,len(df)):
    predictor=df.iloc[i:i+1,:]
    #print(predictor)
    res=model.predict(predictor)
    ls.append(res[0])

In [46]:
print(d)

        s_2      s_3      s_4    s_6     s_7      s_8      s_9   s_11    s_12  \
0    643.86  1612.86  1393.95  21.60  554.62  2388.08  9145.19  47.65  521.64
1    643.23  1571.79  1396.64  21.60  554.84  2388.00  9111.08  47.07  519.20
2    643.33  1595.09  1411.49  21.61  551.67  2388.41  9139.12  48.14  520.57
3    644.36  1595.17  1387.35  21.60  553.97  2388.49  9099.48  46.96  518.78
4    642.10  1595.80  1404.48  21.61  553.03  2388.34  9140.20  46.92  520.74
..      ...      ...      ...    ...     ...      ...      ...    ...     ...
316  642.85  1612.90  1389.54  21.60  555.41  2387.93  9070.16  47.49  522.33
317  644.23  1574.47  1424.53  21.61  553.58  2387.99  9139.75  47.11  518.79
318  641.73  1573.36  1438.41  21.60  551.46  2388.46  9095.43  47.65  519.73
319  642.63  1602.41  1417.46  21.60  553.37  2388.03  9081.83  47.01  520.32
320  642.22  1581.31  1399.92  21.60  552.98  2388.27  9043.06  48.25  518.86

        s_13     s_14  s_15    s_17   s_20   s_21
0    2388.13  8199.43  8.57  398.99  38.96  23.41
1    2388.56  8142.23  8.46  398.07  38.93  23.11
2    2388.49  8154.84  8.42  397.69  39.33  22.94
3    2388.19  8112.17  8.39  399.65  39.30  23.51
4    2388.51  8280.31  8.51  391.41  39.09  23.36
..       ...      ...   ...     ...    ...    ...
316  2388.23  8284.55  8.43  397.41  38.59  23.57
317  2388.13  8166.26  8.58  395.30  38.86  22.92
318  2387.95  8291.51  8.37  394.00  39.14  23.27
319  2388.08  8188.83  8.50  391.23  38.23  23.07
320  2388.10  8282.39  8.33  393.90  38.71  23.47

[321 rows x 15 columns]

In [57]:
import numpy as np
d['rul']=ls

print(d)

        s_2      s_3      s_4    s_6     s_7      s_8      s_9   s_11    s_12  \
0    643.86  1612.86  1393.95  21.60  554.62  2388.08  9145.19  47.65  521.64
1    643.23  1571.79  1396.64  21.60  554.84  2388.00  9111.08  47.07  519.20
2    643.33  1595.09  1411.49  21.61  551.67  2388.41  9139.12  48.14  520.57
3    644.36  1595.17  1387.35  21.60  553.97  2388.49  9099.48  46.96  518.78
4    642.10  1595.80  1404.48  21.61  553.03  2388.34  9140.20  46.92  520.74
..      ...      ...      ...    ...     ...      ...      ...    ...     ...
316  642.85  1612.90  1389.54  21.60  555.41  2387.93  9070.16  47.49  522.33
317  644.23  1574.47  1424.53  21.61  553.58  2387.99  9139.75  47.11  518.79
318  641.73  1573.36  1438.41  21.60  551.46  2388.46  9095.43  47.65  519.73
319  642.63  1602.41  1417.46  21.60  553.37  2388.03  9081.83  47.01  520.32
320  642.22  1581.31  1399.92  21.60  552.98  2388.27  9043.06  48.25  518.86

        s_13     s_14  s_15    s_17   s_20   s_21         rul
0    2388.13  8199.43  8.57  398.99  38.96  23.41   63.970355
1    2388.56  8142.23  8.46  398.07  38.93  23.11   93.682303
2    2388.49  8154.84  8.42  397.69  39.33  22.94   40.236968
3    2388.19  8112.17  8.39  399.65  39.30  23.51  116.290572
4    2388.51  8280.31  8.51  391.41  39.09  23.36   70.266300
..       ...      ...   ...     ...    ...    ...         ...
316  2388.23  8284.55  8.43  397.41  38.59  23.57  104.334748
317  2388.13  8166.26  8.58  395.30  38.86  22.92   45.735767
318  2387.95  8291.51  8.37  394.00  39.14  23.27   52.508522
319  2388.08  8188.83  8.50  391.23  38.23  23.07   47.891733
320  2388.10  8282.39  8.33  393.90  38.71  23.47   79.314632

[321 rows x 16 columns]

In [58]:


d.to_csv('file1.csv')